// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: files/files.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File to upload.
	File []byte `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// user identifier.
	User          string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_files_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UploadRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type UploadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// file ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// file name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// file size.
	Size uint32 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// file extension.
	Extension string `protobuf:"bytes,4,opt,name=extension,proto3" json:"extension,omitempty"`
	// file mime type.
	MimeType string `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// user identifier.
	CreatedBy string `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// file created at.
	CreatedAt     uint32 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_files_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadResponse) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *UploadResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *UploadResponse) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetFileQuery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the file to preview, obtained from the File Upload API response.
	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	// Whether to force download the file as an attachment. Default is false (preview in browser).
	AsAttachment  bool `protobuf:"varint,2,opt,name=as_attachment,json=asAttachment,proto3" json:"as_attachment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileQuery) Reset() {
	*x = GetFileQuery{}
	mi := &file_files_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileQuery) ProtoMessage() {}

func (x *GetFileQuery) ProtoReflect() protoreflect.Message {
	mi := &file_files_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileQuery.ProtoReflect.Descriptor instead.
func (*GetFileQuery) Descriptor() ([]byte, []int) {
	return file_files_files_proto_rawDescGZIP(), []int{2}
}

func (x *GetFileQuery) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetFileQuery) GetAsAttachment() bool {
	if x != nil {
		return x.AsAttachment
	}
	return false
}

var File_files_files_proto protoreflect.FileDescriptor

const file_files_files_proto_rawDesc = "" +
	"\n" +
	"\x11files/files.proto\x12\vworkflow.v1\"7\n" +
	"\rUploadRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"\xc1\x01\n" +
	"\x0eUploadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x1c\n" +
	"\textension\x18\x04 \x01(\tR\textension\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\rR\tcreatedAt\"L\n" +
	"\fGetFileQuery\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12#\n" +
	"\ras_attachment\x18\x02 \x01(\bR\fasAttachmentB\x93\x01\n" +
	"\x0fcom.workflow.v1B\n" +
	"FilesProtoP\x01Z'github.com/openexw/dify-go/api/files/v1\xa2\x02\x03WXX\xaa\x02\vWorkflow.V1\xca\x02\vWorkflow\\V1\xe2\x02\x17Workflow\\V1\\GPBMetadata\xea\x02\fWorkflow::V1b\x06proto3"

var (
	file_files_files_proto_rawDescOnce sync.Once
	file_files_files_proto_rawDescData []byte
)

func file_files_files_proto_rawDescGZIP() []byte {
	file_files_files_proto_rawDescOnce.Do(func() {
		file_files_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_files_files_proto_rawDesc), len(file_files_files_proto_rawDesc)))
	})
	return file_files_files_proto_rawDescData
}

var file_files_files_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_files_files_proto_goTypes = []any{
	(*UploadRequest)(nil),  // 0: workflow.v1.UploadRequest
	(*UploadResponse)(nil), // 1: workflow.v1.UploadResponse
	(*GetFileQuery)(nil),   // 2: workflow.v1.GetFileQuery
}
var file_files_files_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_files_files_proto_init() }
func file_files_files_proto_init() {
	if File_files_files_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_files_files_proto_rawDesc), len(file_files_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_files_files_proto_goTypes,
		DependencyIndexes: file_files_files_proto_depIdxs,
		MessageInfos:      file_files_files_proto_msgTypes,
	}.Build()
	File_files_files_proto = out.File
	file_files_files_proto_goTypes = nil
	file_files_files_proto_depIdxs = nil
}
