// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: workflow/v1/workflow.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseMode int32

const (
	ResponseMode_ResponseMode_Unspecified ResponseMode = 0
	ResponseMode_streaming                ResponseMode = 1
	ResponseMode_blocking                 ResponseMode = 2
)

// Enum value maps for ResponseMode.
var (
	ResponseMode_name = map[int32]string{
		0: "ResponseMode_Unspecified",
		1: "streaming",
		2: "blocking",
	}
	ResponseMode_value = map[string]int32{
		"ResponseMode_Unspecified": 0,
		"streaming":                1,
		"blocking":                 2,
	}
)

func (x ResponseMode) Enum() *ResponseMode {
	p := new(ResponseMode)
	*p = x
	return p
}

func (x ResponseMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseMode) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_v1_workflow_proto_enumTypes[0].Descriptor()
}

func (ResponseMode) Type() protoreflect.EnumType {
	return &file_workflow_v1_workflow_proto_enumTypes[0]
}

func (x ResponseMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseMode.Descriptor instead.
func (ResponseMode) EnumDescriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_Status_Unspecified Status = 0
	Status_running            Status = 1
	Status_succeeded          Status = 2
	Status_failed             Status = 3
	Status_stopped            Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Status_Unspecified",
		1: "running",
		2: "succeeded",
		3: "failed",
		4: "stopped",
	}
	Status_value = map[string]int32{
		"Status_Unspecified": 0,
		"running":            1,
		"succeeded":          2,
		"failed":             3,
		"stopped":            4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_v1_workflow_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_workflow_v1_workflow_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{1}
}

type RunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response mode. Cloudflare timeout is 100s for blocking.
	ResponseMode ResponseMode `protobuf:"varint,1,opt,name=response_mode,json=responseMode,proto3,enum=workflow.v1.ResponseMode" json:"response_mode,omitempty"`
	// User identifier.
	User          string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetResponseMode() ResponseMode {
	if x != nil {
		return x.ResponseMode
	}
	return ResponseMode_ResponseMode_Unspecified
}

func (x *RunRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type RunBlockingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Workflow run ID.
	WorkflowRunId string  `protobuf:"bytes,1,opt,name=workflow_run_id,json=workflowRunId,proto3" json:"workflow_run_id,omitempty"`
	TaskId        string  `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Data          *Detail `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunBlockingResponse) Reset() {
	*x = RunBlockingResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunBlockingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBlockingResponse) ProtoMessage() {}

func (x *RunBlockingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBlockingResponse.ProtoReflect.Descriptor instead.
func (*RunBlockingResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *RunBlockingResponse) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *RunBlockingResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RunBlockingResponse) GetData() *Detail {
	if x != nil {
		return x.Data
	}
	return nil
}

type Detail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=workflow.v1.Status" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinishedAt    string                 `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Outputs       []byte                 `protobuf:"bytes,7,opt,name=outputs,proto3" json:"outputs,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,8,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalSteps    int32                  `protobuf:"varint,9,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Detail) Reset() {
	*x = Detail{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detail) ProtoMessage() {}

func (x *Detail) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detail.ProtoReflect.Descriptor instead.
func (*Detail) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *Detail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Detail) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Detail) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Status_Unspecified
}

func (x *Detail) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Detail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Detail) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *Detail) GetOutputs() []byte {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Detail) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Detail) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

type StopRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task ID from the streaming chunk.
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=-,proto3" json:"task_id,omitempty"`
	// User identifier.
	User          string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *StopRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StopRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type StopResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation successful.
	Result        string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *StopResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type LogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keyword to search.
	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// Status to filter.
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=workflow.v1.Status" json:"status,omitempty"`
	// Page number. default is 1.
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Number of items per page. default is 20.
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *LogsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *LogsRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Status_Unspecified
}

func (x *LogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	Logs          []*Log                 `protobuf:"bytes,5,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsResponse) Reset() {
	*x = LogsResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsResponse) ProtoMessage() {}

func (x *LogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsResponse.ProtoReflect.Descriptor instead.
func (*LogsResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *LogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LogsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *LogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *LogsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *LogsResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type Log struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowRun      *Detail                `protobuf:"bytes,2,opt,name=workflow_run,json=workflowRun,proto3" json:"workflow_run,omitempty"`
	CreatedFrom      string                 `protobuf:"bytes,3,opt,name=created_from,json=createdFrom,proto3" json:"created_from,omitempty"`
	CreatedByRole    string                 `protobuf:"bytes,4,opt,name=created_by_role,json=createdByRole,proto3" json:"created_by_role,omitempty"`
	CreatedByAccount string                 `protobuf:"bytes,5,opt,name=created_by_account,json=createdByAccount,proto3" json:"created_by_account,omitempty"`
	CreatedByEndUser *Log_User              `protobuf:"bytes,6,opt,name=created_by_end_user,json=createdByEndUser,proto3" json:"created_by_end_user,omitempty"`
	CreatedAt        uint32                 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *Log) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Log) GetWorkflowRun() *Detail {
	if x != nil {
		return x.WorkflowRun
	}
	return nil
}

func (x *Log) GetCreatedFrom() string {
	if x != nil {
		return x.CreatedFrom
	}
	return ""
}

func (x *Log) GetCreatedByRole() string {
	if x != nil {
		return x.CreatedByRole
	}
	return ""
}

func (x *Log) GetCreatedByAccount() string {
	if x != nil {
		return x.CreatedByAccount
	}
	return ""
}

func (x *Log) GetCreatedByEndUser() *Log_User {
	if x != nil {
		return x.CreatedByEndUser
	}
	return nil
}

func (x *Log) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Log_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IsAnonymous   bool                   `protobuf:"varint,3,opt,name=is_anonymous,json=isAnonymous,proto3" json:"is_anonymous,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log_User) Reset() {
	*x = Log_User{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_User) ProtoMessage() {}

func (x *Log_User) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_User.ProtoReflect.Descriptor instead.
func (*Log_User) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Log_User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Log_User) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Log_User) GetIsAnonymous() bool {
	if x != nil {
		return x.IsAnonymous
	}
	return false
}

func (x *Log_User) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_workflow_v1_workflow_proto protoreflect.FileDescriptor

const file_workflow_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1aworkflow/v1/workflow.proto\x12\vworkflow.v1\"`\n" +
	"\n" +
	"RunRequest\x12>\n" +
	"\rresponse_mode\x18\x01 \x01(\x0e2\x19.workflow.v1.ResponseModeR\fresponseMode\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"\x7f\n" +
	"\x13RunBlockingResponse\x12&\n" +
	"\x0fworkflow_run_id\x18\x01 \x01(\tR\rworkflowRunId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12'\n" +
	"\x04data\x18\x03 \x01(\v2\x13.workflow.v1.DetailR\x04data\"\x9a\x02\n" +
	"\x06Detail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.workflow.v1.StatusR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\tR\n" +
	"finishedAt\x12\x18\n" +
	"\aoutputs\x18\a \x01(\fR\aoutputs\x12!\n" +
	"\ftotal_tokens\x18\b \x01(\x05R\vtotalTokens\x12\x1f\n" +
	"\vtotal_steps\x18\t \x01(\x05R\n" +
	"totalSteps\"5\n" +
	"\vStopRequest\x12\x12\n" +
	"\atask_id\x18\x01 \x01(\tR\x01-\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"&\n" +
	"\fStopResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"~\n" +
	"\vLogsRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.workflow.v1.StatusR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x8f\x01\n" +
	"\fLogsResponse\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\x12$\n" +
	"\x04logs\x18\x05 \x03(\v2\x10.workflow.v1.LogR\x04logs\"\x99\x03\n" +
	"\x03Log\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\fworkflow_run\x18\x02 \x01(\v2\x13.workflow.v1.DetailR\vworkflowRun\x12!\n" +
	"\fcreated_from\x18\x03 \x01(\tR\vcreatedFrom\x12&\n" +
	"\x0fcreated_by_role\x18\x04 \x01(\tR\rcreatedByRole\x12,\n" +
	"\x12created_by_account\x18\x05 \x01(\tR\x10createdByAccount\x12D\n" +
	"\x13created_by_end_user\x18\x06 \x01(\v2\x15.workflow.v1.Log.UserR\x10createdByEndUser\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\rR\tcreatedAt\x1al\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fis_anonymous\x18\x03 \x01(\bR\visAnonymous\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId*I\n" +
	"\fResponseMode\x12\x1c\n" +
	"\x18ResponseMode_Unspecified\x10\x00\x12\r\n" +
	"\tstreaming\x10\x01\x12\f\n" +
	"\bblocking\x10\x02*U\n" +
	"\x06Status\x12\x16\n" +
	"\x12Status_Unspecified\x10\x00\x12\v\n" +
	"\arunning\x10\x01\x12\r\n" +
	"\tsucceeded\x10\x02\x12\n" +
	"\n" +
	"\x06failed\x10\x03\x12\v\n" +
	"\astopped\x10\x04B\x99\x01\n" +
	"\x0fcom.workflow.v1B\rWorkflowProtoP\x01Z*github.com/openexw/dify-go/api/workflow/v1\xa2\x02\x03WXX\xaa\x02\vWorkflow.V1\xca\x02\vWorkflow\\V1\xe2\x02\x17Workflow\\V1\\GPBMetadata\xea\x02\fWorkflow::V1b\x06proto3"

var (
	file_workflow_v1_workflow_proto_rawDescOnce sync.Once
	file_workflow_v1_workflow_proto_rawDescData []byte
)

func file_workflow_v1_workflow_proto_rawDescGZIP() []byte {
	file_workflow_v1_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_v1_workflow_proto_rawDesc), len(file_workflow_v1_workflow_proto_rawDesc)))
	})
	return file_workflow_v1_workflow_proto_rawDescData
}

var file_workflow_v1_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_workflow_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_workflow_v1_workflow_proto_goTypes = []any{
	(ResponseMode)(0),           // 0: workflow.v1.ResponseMode
	(Status)(0),                 // 1: workflow.v1.Status
	(*RunRequest)(nil),          // 2: workflow.v1.RunRequest
	(*RunBlockingResponse)(nil), // 3: workflow.v1.RunBlockingResponse
	(*Detail)(nil),              // 4: workflow.v1.Detail
	(*StopRequest)(nil),         // 5: workflow.v1.StopRequest
	(*StopResponse)(nil),        // 6: workflow.v1.StopResponse
	(*LogsRequest)(nil),         // 7: workflow.v1.LogsRequest
	(*LogsResponse)(nil),        // 8: workflow.v1.LogsResponse
	(*Log)(nil),                 // 9: workflow.v1.Log
	(*Log_User)(nil),            // 10: workflow.v1.Log.User
}
var file_workflow_v1_workflow_proto_depIdxs = []int32{
	0,  // 0: workflow.v1.RunRequest.response_mode:type_name -> workflow.v1.ResponseMode
	4,  // 1: workflow.v1.RunBlockingResponse.data:type_name -> workflow.v1.Detail
	1,  // 2: workflow.v1.Detail.status:type_name -> workflow.v1.Status
	1,  // 3: workflow.v1.LogsRequest.status:type_name -> workflow.v1.Status
	9,  // 4: workflow.v1.LogsResponse.logs:type_name -> workflow.v1.Log
	4,  // 5: workflow.v1.Log.workflow_run:type_name -> workflow.v1.Detail
	10, // 6: workflow.v1.Log.created_by_end_user:type_name -> workflow.v1.Log.User
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_workflow_v1_workflow_proto_init() }
func file_workflow_v1_workflow_proto_init() {
	if File_workflow_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_v1_workflow_proto_rawDesc), len(file_workflow_v1_workflow_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_v1_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_v1_workflow_proto_depIdxs,
		EnumInfos:         file_workflow_v1_workflow_proto_enumTypes,
		MessageInfos:      file_workflow_v1_workflow_proto_msgTypes,
	}.Build()
	File_workflow_v1_workflow_proto = out.File
	file_workflow_v1_workflow_proto_goTypes = nil
	file_workflow_v1_workflow_proto_depIdxs = nil
}
